#!/usr/bin/env python

import os
import sys

from server.web import app

sys.path.append(".")

port = int(os.environ.get('SERVER_WEB_PORT', 5001))
debug = 'SERVER_DEBUG' in os.environ

app.run(host='0.0.0.0', port=port, debug=debug)
